parameters:
#    avtenta_angular.example.class: Avtenta\AngularBundle\Example

services:
#    avtenta_angular.example:
#        class: %avtenta_angular.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    in_memory_user_provider:
        alias: security.user.provider.concrete.in_memory

    wsse.security.authentication.provider:
        class:  Avtenta\AngularBundle\Security\Authentication\Provider\WsseProvider
        arguments: ["@in_memory_user_provider", "%kernel.cache_dir%/security/nonces"]

    wsse.security.authentication.listener:
        class:  Avtenta\AngularBundle\Security\Firewall\WsseListener
        arguments: ["@security.context", "@security.authentication.manager"]

    request_book_service:
        class: Avtenta\AngularBundle\Consumer\RequestBookConsumer
        arguments: [@logger]

    book_messaging_system:
        class: Avtenta\AngularBundle\Producer\BookMessageSystem
        arguments: ["@old_sound_rabbit_mq.request_book_producer"]

